name: GitHub Actions Demo

on: 
  push:
    branches:
      - main
    paths-ignore: [.github/**]  
  pull_request_target:
    branches:
      - main
  schedule:
    - cron: "15 6 * * SUN"
  workflow_dispatch:    

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running ${{ github.event_name }}
          echo "On branch: ${{ github.ref }}"

      - uses: actions/checkout@v4

      - name: List all files
        run: |
          echo "Listing all files in repo ${{ github.repository }}
          tree


    

